# Site settings
title: 5 Pin Bowling Companion
email: contact@josephroque.ca
description: > # this means to ignore newlines until "baseurl:"
  Improve your 5 pin bowling game! Track your average and a tonne of statistics
  to help make yourself a better bowler.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bowlingcompanion.ca" # the base hostname & protocol for your site
twitter_username: josephroquedev
github_username:  josephroquedev
author: Joseph Roque

# Build settings
markdown: kramdown
