# Site settings
title: 5 Pin Bowling Companion
description: > # this means to ignore newlines until "baseurl:"
  Improve your 5 pin bowling game! Track your average and a tonne of statistics
  to help make yourself a better bowler.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bowlingcompanion.ca" # the base hostname & protocol for your site
twitter_username: autoreleasefool
github_username:  autoreleasefool
author: Joseph Roque

# Build settings
markdown: kramdown
